language: generic
sudo: false
git:
  submodules: false

before_install:
  - git clone -b master --single-branch https://github.com/wr-tty/EasyMiner-Performance-Tests.git EasyMiner-Performance-Tests
  - git clone -b master --single-branch https://github.com/wr-tty/EasyMiner-Performance-Testing-Env.git EasyMiner-Performance-Testing-Env
  - cd EasyMiner-Performance-Testing-Env

services:
  - docker

script:
  - docker-compose up --exit-code-from taurus --force-recreate taurus

after_script:
